### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by craigsheen** [craigsheen/atom-guard-rspec#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: [guard-rspec](https://github.com/craigsheen/atom-guard-rspec) package, v0.2.0
### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At /Users/craigsheen/development/atom-packages/guard-rspec/lib/output-helper.coffee:31

TypeError: Cannot read property '1' of null
    at OutputHelper.formatError (/Users/craigsheen/development/atom-packages/guard-rspec/lib/output-helper.coffee:31:46)
    at /Users/craigsheen/development/atom-packages/guard-rspec/lib/output-helper.coffee:22:19
    at Array.map (native)
    at OutputHelper.gatherErrors (/Users/craigsheen/development/atom-packages/guard-rspec/lib/output-helper.coffee:21:32)
    at OutputHelper.check (/Users/craigsheen/development/atom-packages/guard-rspec/lib/output-helper.coffee:12:14)
    at GuardRspecView.module.exports.GuardRspecView.handleOutput (/Users/craigsheen/development/atom-packages/guard-rspec/lib/guard-rspec-view.coffee:32:18)
    at Socket.<anonymous> (/Users/craigsheen/development/atom-packages/guard-rspec/lib/guard-rspec-view.coffee:1:1)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```
### Commands

```
     -1:10.2.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:10.2.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:10.2.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:04.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:43.6.0 pane:show-item-2 (atom-text-editor.editor.is-focused)
     -0:39.8.0 pane:show-item-1 (atom-text-editor.editor.is-focused)
     -0:31.2.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:30.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:28.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:27.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:26 core:move-up (atom-text-editor.editor.is-focused)
     -0:25.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:20.8.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:18.4.0 editor:move-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
  2x -0:18.1.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -0:16.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.26
color-picker, v2.1.1
guard-rspec, v0.2.0
language-haml, v0.23.15
linter, v1.11.4
linter-rubocop, v0.4.7
pigments, v0.24.5

# Dev
No dev packages
```

**Comment by craigsheen** [comment]
Fixed: https://github.com/craigsheen/atom-guard-rspec/commit/bf77cea5f9fc74bbc11fcf4a532a269ef2e69d39
